services:
  nginx:
    image: nginx:alpine

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend
      - backend

    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: ghcr.io/AryanGKulkarni/aum-erp-backend:latest
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    image: ghcr.io/AryanGKulkarni/aum-erp-frontend:latest
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data:
