import {
  Body,
  Controller,
  Get,
  Post,
  Patch,
  Param,
  ParseIntPipe,
  BadRequestException,
  NotFoundException,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateMachineDto } from './dto/create-machine.dto';
import { UpdateMachineDto } from './dto/update-machine.dto';

@Controller('machine')
export class MachineController {
  constructor(private readonly prisma: PrismaService) {}

  @Get()
  findAll() {
    return this.prisma.machine.findMany({
      orderBy: { machineName: 'asc' },
    });
  }

  @Post()
  async create(@Body() dto: CreateMachineDto) {
    if (!dto.machineName?.trim()) {
      throw new BadRequestException('machineName is required');
    }
    if (!dto.machineType) {
      throw new BadRequestException('machineType is required');
    }

    return this.prisma.machine.create({
      // availableHrsPerMonth is generated by Postgres and must not be written.
      data: {
        machineName: dto.machineName,
        machineType: dto.machineType,
        capacityTons: dto.capacityTons,
        availableHrsPerDay: dto.availableHrsPerDay,
        workingDaysPerMonth: dto.workingDaysPerMonth,
        status: dto.status,
      },
    });
  }

  @Patch(':id')
  async update(@Param('id', ParseIntPipe) id: number, @Body() dto: UpdateMachineDto) {
    if (dto.machineName !== undefined && !dto.machineName.trim()) {
      throw new BadRequestException('machineName cannot be empty');
    }

    try {
      return await this.prisma.machine.update({
        where: { machineId: id },
        data: {
          machineName: dto.machineName,
          machineType: dto.machineType,
          capacityTons: dto.capacityTons,
          availableHrsPerDay: dto.availableHrsPerDay,
          workingDaysPerMonth: dto.workingDaysPerMonth,
          status: dto.status,
        },
      });
    } catch (err: any) {
      if (err?.code === 'P2025') {
        throw new NotFoundException(`Machine #${id} not found`);
      }
      throw err;
    }
  }
}
